name: flutter_longdistance_bus_app
description: Ứng dụng đặt vé xe khách đường dài sử dụng Flutter + Firebase.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI cơ bản
  cupertino_icons: ^1.0.6
  intl: ^0.20.2

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3

  # Tiện ích
  uuid: ^4.3.3

  # Giao diện đẹp & hiện đại
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.0
  smooth_page_indicator: ^1.1.0
  awesome_dialog: ^3.2.0
  fluttertoast: ^9.0.0
  shimmer: ^3.0.0
  curved_navigation_bar: ^1.0.3
  get: ^4.6.6

  # QR code
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
